### ISSUE TITLE
[Feature] Add existing to CloudinaryUploadWidgetInfo interface

### ISSUE THREAD

**Issue by MateoWartelle** [cloudinary-community/cloudinary-util#152]
# **Feature Request**

## **Is your feature request related to a problem? Please describe.**

I wouldn't say it is necessarily a problem it is just missing from the interface but appears in the cloudinary upload response.

## **Describe the solution you'd like**

Add existing: boolean to CloudinaryUploadWidgetInfo

## **Describe alternatives you've considered**

No alternatives considered.

**Comment by colbyfayock** [comment]
hey thanks @MateoWartelle - just to be clear

on this: https://github.com/colbyfayock/cloudinary-util/blob/main/packages/types/src/types/cloudinary-upload-widget.d.ts#L117

add:
```
existing: boolean;
```
correct?

can you show me an example response and how you got it? does this occur when you upload the same asset 2 times with overwrite: false? or perhaps by trying to set the public ID manually?
