### ISSUE TITLE
[Feature] Add list of gravity options to TS definition

### ISSUE THREAD

**Issue by colbyfayock** [cloudinary-community/cloudinary-util#170]
# **Feature Request**

## **Is your feature request related to a problem? Please describe.**

To make it easier to specify a gravity, we can define all the gravity options in TS so they pop up with autocomplete.

https://github.com/cloudinary-community/cloudinary-util/blob/main/packages/url-loader/src/constants/parameters.ts#L144

**Comment by nickytonline** [comment]
Hey @colbyfayock, just following up post our live stream. I can pick this up.
