### ISSUE TITLE
[Feature] Add cloudinaryAnalytics to Video Player types

### ISSUE THREAD

**Issue by colbyfayock** [cloudinary-community/cloudinary-util#171]
## What?
https://cloudinary.com/documentation/video_player_api_reference#ads_and_analytics

## Where?
https://github.com/cloudinary-community/cloudinary-util/blob/main/packages/types/src/types/cloudinary-video-player.ts

**Comment by nooras** [comment]
Hey @colbyfayock 
I am interested in this task can you please assign me ?

**Comment by nooras** [comment]
Hey @colbyfayock 
Kindly please review the PR #208 
Let me know if any changes are required
