### ISSUE TITLE
[Feature] Write out Typescript Types for Cloudinary Product Gallery Widget

### ISSUE THREAD

**Issue by colbyfayock** [cloudinary-community/cloudinary-util#199]
# **Feature Request**

## **Is your feature request related to a problem? Please describe.**

Work through the Product Gallery reference documentation to create a Type interface for the Product Gallery Widget

https://cloudinary.com/documentation/product_gallery_reference

This should look similar to how we've built the interface for the Video Player:

https://github.com/cloudinary-community/cloudinary-util/blob/main/packages/types/src/types/cloudinary-video-player.ts

And the Upload Widget:

https://github.com/cloudinary-community/cloudinary-util/blob/main/packages/types/src/types/cloudinary-upload-widget.ts

These types will live in the @cloudinary-util/types package, which live in:

https://github.com/cloudinary-community/cloudinary-util/tree/main/packages/types/src/types

**Comment by Mrinank-Bhowmick** [comment]
I am working on this issue 🚀
