### ISSUE TITLE
[Feature] TSConfig Updates

### ISSUE THREAD

**Issue by colbyfayock** [cloudinary-community/cloudinary-util#72]
# **Feature Request**

## **Is your feature request related to a problem? Please describe.**

* target `es2021` or `esnext`
* lib should default to target, does that mean we dont need to separately define it? but if defined, update to target value (in node14.json)
* moduleResolution `bundler` (because tsup and next) or `node16` or `nodenext` (in base.json)
* ~strict if reasonable~ already strict
* ~noImplicitAny if reasonable, but due to missing types for some cloudinary utilities it may have to wait~ adding to beta

**Comment by Keith-Web3** [comment]
Hey @colbyfayock, can I work on this issue?

**Comment by colbyfayock** [comment]
hey @Keith-Web3 sure!
