### ISSUE TITLE
[Feature] Add support for all color values to optionally use #hex

### ISSUE THREAD

**Issue by colbyfayock** [cloudinary-community/cloudinary-util#95]
# **Feature Request**

## **Is your feature request related to a problem? Please describe.**

All color values should allow the use of hex codes like `#ff00ff`

## **Describe the solution you'd like**

This would then be transformed to a cloudinary value of `rgb:f00ff` during URL generation

For instance:
```
{
  background: '#ff00ff'
}
```

<img width="866" alt="image" src="https://github.com/user-attachments/assets/8ecaf642-15a5-4ede-bec9-08fbb5a9a147">

the requirement is to use `rgba:ff00ff` but it would be nice for convenience to use `#` as its standard in HTML/CSS

**Comment by AvaterClasher** [comment]
@colbyfayock Can you explain a bit more about this issue because i think this is implemented or i might be wrong -
https://github.com/cloudinary-community/cloudinary-util/blob/4086730a5186b142a4c9afc15c1b199a3f738935/packages/util/src/lib/colors.ts#L14

**Comment by colbyfayock** [comment]
apologies looks like youre right from what i can tell as well. I'll close this, let me know if there are any other issues you're interested in working on!
